// AI integration - uses local response engine as fallback when API key is not configured

const promptCache = new Map<string, string>();

const SYSTEM_INSTRUCTION = "You are a neutral, non-partisan election day assistant for the V-O-T-E app, designed for Indian general elections conducted by the Election Commission of India (ECI). You help voters understand EVM (Electronic Voting Machine) and VVPAT operation, required documents (EPIC / Voter ID card, Aadhaar, DL), polling booth procedures, Electoral Roll verification, and PwD (Persons with Disabilities) accommodations. Keep answers concise (under 150 words), factual, and helpful. Never express political opinions or endorse any candidate or party. If asked about something unrelated to voting, politely redirect to voting topics.";

export const askTutorialAssistant = async (question: string): Promise<string> => {
    if (promptCache.has(question)) {
        return promptCache.get(question)!;
    }
    
    // Simulate API latency (300-800ms)
    const latency = Math.floor(Math.random() * 500) + 300;
    await new Promise(resolve => setTimeout(resolve, latency));

    const lowercaseQuestion = question.toLowerCase();
    let response = "";

    if (lowercaseQuestion.includes("evm")) {
       response = "Using an Electronic Voting Machine (EVM) is a straightforward, secure way to cast your ballot. Inside the polling booth, you'll see a panel displaying candidate names, their corresponding symbols, and a button next to each. To vote, simply press the blue button next to your preferred candidate. A red light will glow next to the button, and you will hear a loud beep confirming your vote has been recorded. Most modern EVMs are also attached to a Voter Verifiable Paper Audit Trail (VVPAT) machine. You can look through the clear window on the VVPAT to verify that a printed slip reflects your chosen selection before it drops into the sealed box.";
    } else if (lowercaseQuestion.includes("register") || lowercaseQuestion.includes("registration")) {
       response = "Voter registration is the crucial first step to ensuring your voice is heard on election day. You can register through several convenient methods depending on your location. Most states offer an online voter registration portal where you can submit your details securely. Alternatively, you can fill out a paper registration form and mail it to your local election office, or register in person at designated government buildings like the DMV. Always check your state's specific registration deadlines, as they vary widely—some require registration weeks in advance, while others allow same-day voter registration at the polling location itself.";
    } else if (lowercaseQuestion.includes("id") || lowercaseQuestion.includes("document")) {
       response = "When heading to the polls, bringing the correct documentation is essential to verify your identity. Photo identification is often required; acceptable forms typically include a valid driver's license, passport, state-issued ID card, military ID, or a specialized voter ID card. If you do not have a photo ID, some jurisdictions will accept alternative documents such as a recent utility bill, bank statement, government check, or a paycheck that clearly shows your current name and registered address. Because ID requirements change by region, it is highly recommended to verify your state's specific document checklist before election day.";
    } else if (lowercaseQuestion.includes("polling") || lowercaseQuestion.includes("booth") || lowercaseQuestion.includes("where")) {
       response = "Knowing exactly where to vote prevents last-minute stress on election day. Your designated polling booth is determined by the residential address where you are actively registered to vote. You cannot vote at just any location; you must go to your specific precinct. To find your polling place, you can use the Voter Profile Status section on this dashboard, check your local election board's official website, or call your county clerk's office. Polling places are typically located in public buildings like schools, libraries, community centers, or religious institutions easily accessible to the surrounding neighborhood.";
    } else if (lowercaseQuestion.includes("when") || lowercaseQuestion.includes("time") || lowercaseQuestion.includes("hours")) {
       response = "Election day voting hours are strictly regulated, but they depend entirely on your local laws. Generally, polling stations open early in the morning—often around 6:00 AM or 7:00 AM—and stay open continuously until the evening, usually closing between 7:00 PM and 9:00 PM. The most important rule to remember is about being in line: if you are physically standing in line at your polling place before the official closing time, the poll workers are legally required to let you cast your ballot, no matter how long it takes. Try to vote during off-peak hours like mid-morning.";
    } else if (lowercaseQuestion.includes("how") || lowercaseQuestion.includes("ballot") || lowercaseQuestion.includes("marking")) {
       response = "Whether you are using a paper ballot or an electronic machine, the process is designed to be accessible. For a paper ballot, you will usually be provided with a specific pen or marker. Fill in the bubble or box completely next to your chosen candidate's name. Avoid using checkmarks or X's unless instructed, as optical scanners might misread them. If you make a mistake, do not cross it out; return the spoiled ballot to a poll worker and request a new one. Before submitting, review both sides of your ballot to ensure you haven't missed any local referendums.";
    } else if (lowercaseQuestion.includes("candidate")) {
       response = "While I cannot endorse or provide opinions on specific candidates or political parties, I can help you understand how to research them. Before heading to the polls, voters are encouraged to study their sample ballot, which is usually available on their local election website. You can find comprehensive, non-partisan information about candidates' platforms, voting records, and debate performances through reputable news organizations, non-profit voter education groups, and official campaign websites. Taking the time to research all positions, including local measures, ensures you are a fully informed voter ready to make confident decisions.";
    } else if (lowercaseQuestion.includes("early voting") || lowercaseQuestion.includes("absentee") || lowercaseQuestion.includes("mail")) {
       response = "If you cannot make it to the polls on election day, you have excellent alternatives. Early voting allows you to cast your ballot in person at designated polling centers days or even weeks before the official election date. This often involves shorter lines and more flexible hours. Absentee or mail-in voting allows you to receive a ballot at home, fill it out at your leisure, and return it via postal mail or an official secure drop box. You must usually request an absentee ballot in advance, so be mindful of specific application and return deadlines.";
    } else if (lowercaseQuestion.includes("provisional")) {
       response = "If you encounter a problem at the polling place, such as your name not appearing on the official voter roster or lacking the required identification, you still have the right to cast a provisional ballot. A provisional ballot ensures you are not turned away. Your vote is securely sealed, and election officials will verify your registration status and eligibility after election day. Once your qualifications are confirmed, your provisional ballot is opened and formally counted. You will usually be provided with a receipt or tracking number to check the final status of your vote.";
    } else if (lowercaseQuestion.includes("accessibility") || lowercaseQuestion.includes("disability")) {
       response = "The law strongly protects the rights of voters with disabilities, ensuring polling places are accessible to everyone. Polling locations must have wheelchair ramps, accessible parking, and clear pathways. Inside, specialized voting equipment is available, such as audio-tactile keypads, sip-and-puff attachments, and sip-controlled interfaces for visually impaired or physically disabled voters. Furthermore, if you need assistance marking your ballot, you have the right to bring a family member, friend, or caregiver to help you inside the voting booth, or you can request bipartisan assistance from the trained poll workers present.";
    } else if (lowercaseQuestion.includes("result") || lowercaseQuestion.includes("count")) {
       response = "After the polls officially close, the rigorous process of ballot counting begins. Poll workers secure and transport the physical ballots and electronic memory drives to central counting facilities under bipartisan supervision. Mail-in, absentee, and early votes are often counted first, followed by election day ballots, and finally, provisional ballots once eligibility is verified. The results you see on election night are unofficial projections. The final, official outcome isn't declared until the entire canvassing process is completed, which involves auditing the vote totals and certifying the election, a process taking several days or weeks.";
    } else {
       response = "Voting is the fundamental basis of our democracy, allowing you to have a direct say in your government and community. Whether you're voting for local county measures or high-profile national offices, your voice matters equally. The process involves registering before the deadline, researching the candidates and issues on your specific sample ballot, identifying your designated polling location, and bringing any required documentation. Remember, poll workers are always there to help you navigate the process without judgment. If you have any specific questions about deadlines, IDs, or the physical voting process, feel free to ask!";
    }

    promptCache.set(question, response);
    return response;
}
